.TH "Buzzer" 3 "Sistema de seguridad en cámaras frigoríficas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Buzzer
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBBuzzer\fP (int buzzPin, int potPin)"
.br
.ti -1c
.RI "void \fBsetup\fP ()"
.br
.ti -1c
.RI "void \fBupdate\fP ()"
.br
.in -1c

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Sistema de seguridad en cámaras frigoríficas del código fuente\&.
