.TH "main/libraries/DHT11-HW-481/setPin.cpp" 3 "Sistema de seguridad en cámaras frigoríficas" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main/libraries/DHT11-HW-481/setPin.cpp \- Función amiga setPinDHT11\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'DHT11\&.h'\fP
.br
\fR#include 'setPin\&.h'\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBsetPinDHT11\fP (\fBDHT11\fP &sensor, int pin)"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Función amiga setPinDHT11\&. 


.PP
\fBParámetros\fP
.RS 4
\fIDHT11&\fP sensor: recibe una referencia al objeto de la clase \fBDHT11\fP al cual se le cambiará el pin de conexión correspondiente al sensor de temperatura\&. 
.br
\fIint\fP pin: es el nuevo pin para la entrada de datos del sensor de temperatura\&.
.RE
.PP
La función comprueba si el pin es válido, luego 'desactiva' el pin anterior para inicializar el nuevo\&. 
.SH "Documentación de funciones"
.PP 
.SS "void setPinDHT11 (\fBDHT11\fP & sensor, int pin)"
Bloque if-else Controla si el pin ingresado es uno físicamente válido\&. Imprime por puerto serie UART un mensaje de error en caso de no serlo\&.

.PP
pinMode(sensor\&._pin, INPUT) 'Desactiva' el pin anterior\&.

.PP
sensor\&._pin = pin Actualiza el pin\&.

.PP
pinMode(pin, OUTPUT) y digitalWrite(pin, HIGH) Inicializa el nuevo pin como lo hace internamente la clase \fBDHT11\fP

.PP
delay(250) Tiempo de espera a que el sensor se estabilice\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Sistema de seguridad en cámaras frigoríficas del código fuente\&.
